name: build & push docker image
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  review:
    #https://github.com/plantoncloud/javascript-github-workflows/blob/main/.github/workflows/gcp-artifact-registry.build-and-push-docker-image.node.yarnv3.yaml
    uses: plantoncloud/javascript-github-workflows/.github/workflows/gcp-artifact-registry.build-and-push-docker-image.node.yarnv3.yaml@main
    secrets:
      PLANTON_CLOUD_CLIENT_EMAIL: ${{ secrets.PLANTON_CLOUD_CLIENT_EMAIL }}
      PLANTON_CLOUD_CLIENT_SECRET: ${{ secrets.PLANTON_CLOUD_CLIENT_SECRET }}
    with:
      PLANTON_CLOUD_ARTIFACT_STORE_ID: afs-planton-cloud-gcp-uc1
      DOCKER_REPO_HOSTNAME: us-central1-docker.pkg.dev
      CONTAINER_IMAGE_REPO: us-central1-docker.pkg.dev/ca-planton-gcp-sh-zg/afs-planton-cloud-gcp-uc1-docker/github.com/plantoncloud-inc/docs-website
      CONTAINER_IMAGE_TAG: ${{ github.sha }}
      BUILD_DIRECTORY: site
